- name: install nodejs
  hosts: aws
  gather_facts: True
  sudo: True
  tasks:
    - name: Get apt key for nodesource
      command: /usr/bin/wget https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      args:
        chdir: /tmp/
    - name: add repo for nodesource
      apt_repository: repo='deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' update_cache=yes
    - name: install nodejs
      apt: name=nodejs allow_unauthenticated=yes